### ISSUE TITLE
TODO list for error messages

### ISSUE THREAD

**Issue by etiennebacher** [eitsupi/neo-r-polars#11]
1. Repetition of some calls

"Evaluation failed in `$select()`." is repeated, and I couldn't find a way to fix it:

```
pl$DataFrame(x = 1)$select(pl$col("x")$name$suffix(1))
Error:
! Evaluation failed in `$select()`.
Caused by error:
! Evaluation failed in `$select()`.
Caused by error in `pl$col("x")$name$suffix()`:
! Evaluation failed in `$suffix()`.
Caused by error:
! Argument `suffix` must be character, not double
```

2. Some calls appear in the trace but not in the user code, which is confusing

`$collect()` is not called explicitly:

```
pl$DataFrame(x = 1)$select(pl$col("a"))
Error:
! Evaluation failed in `$select()`.
Caused by error:
! Evaluation failed in `$collect()`.
Caused by error:
! ColumnNotFound(ErrString("a\n\nResolved plan until failure:\n\n\t---> FAILED HERE RESOLVING 'select' <---\nDF [\"x\"]; PROJECT */1 COLUMNS; SELECTION: None"))
```

3. Need a way to cleanup raw messages coming from rust-polars

Same code as above, the raw message about "ColumnNotFound" should be cleaned and the formatting should be applied (e.g. apply line breaks instead of `\n`). This can be done with regex but it seems a bit fragile? For instance this code:

```r
[...]
 else {
    "Evaluation failed."
 }
 cnd <- translate_polars_errors(cnd)
 abort(
   msg_body,
   call = call,
   parent = cnd
 )
}

translate_polars_errors <- function(cnd) {
  msg <- cnd$message
  new_msg <- gsub("ErrString\\((.*)\\)", "\\1", msg)

  if (startsWith(new_msg, "ColumnNotFound")) {
    new_msg <- new_msg |>
      gsub("ColumnNotFound\\(", "", x = _) |>
      gsub("Resolved .*", "", x = _) |>
      gsub("\\\\n", "", x = _) |>
      gsub("\"", "", x = _)
    new_msg <- paste("Column(s) not found:", toString(new_msg))
  }

  cnd$message <- new_msg
  cnd
}
```

gives this:

```
pl$DataFrame(x = 1)$select(pl$col("a"))
Error:
! Evaluation failed in `$select()`.
Caused by error:
! Evaluation failed in `$collect()`.
Caused by error:
! Column(s) not found: a
```

**Comment by eitsupi** [comment]
> Same code as above, the raw message about "ColumnNotFound" should be cleaned and the formatting should be applied (e.g. apply line breaks instead of `\n`). This can be done with regex but it seems a bit fragile? For instance this code:

I think this should be formatted on the Rust side.

**Comment by etiennebacher** [comment]
3 is solved. 

1 and 2 are actually the same thing. In 1, the `$select()` call is repeated because we first call it on a DataFrame but it's dispatched to the LazyFrame function.

**Comment by eitsupi** [comment]
It is indeed confusing but correct to see something like `select` twice, so I don't know if it is a good thing to force fix that (it also appears twice in the Python Polars stack trace).

**Comment by etiennebacher** [comment]
I think it's gonna be hard to hide the internal calls in a clean way. Maybe one way to improve it would be to show a `<LazyFrame>` or `<DataFrame>` prefix in the call, so that the error message would be like this for instance?

```r
pl$DataFrame(x = 1)$select(pl$col("x")$name$suffix(1))

Error:
! Evaluation failed in `<DataFrame>$select()`.
Caused by error:
! Evaluation failed in `<LazyFrame>$select()`.
Caused by error in `pl$col("x")$name$suffix()`:
! Evaluation failed in `$suffix()`.
Caused by error:
! Argument `suffix` must be character, not double
```
I don't know if that would be hard to implement though.

Apart from that, I think the error messages are quite good now, point 3 was the most important IMO.

**Comment by etiennebacher** [comment]
Turns out it's not that simple because we run into infinite recursion. If I place this before the `try_fetch()` then it also hides some of the error stack in the message (don't know why). I won't spend more time on this so feel free to close if you won't either

**Comment by eitsupi** [comment]
Yes, I think what we have now is sufficient. I will close it for now. Thanks.
