### ISSUE TITLE
Can't load the package following polars version bump in #19

### ISSUE THREAD

**Issue by etiennebacher** [eitsupi/neo-r-polars#25]
I can compile (i.e. `task build-rust` doesn't fail) but `task build-documents` fails with: 

```
ℹ Loading neopolars
Error in dyn.load(dll_copy_file) : 
  unable to load shared object '/tmp/RtmpIlKnXG/pkgload45a0e67deca3b/neopolars.so':
  /tmp/RtmpIlKnXG/pkgload45a0e67deca3b/neopolars.so: undefined symbol: _Py_Dealloc
Calls: <Anonymous> ... <Anonymous> -> load_dll -> library.dynam2 -> dyn.load
```

Likely due to the bump of polars in https://github.com/eitsupi/neo-r-polars/commit/f6dd46cbb9b1a366a84b830cb322241f72d3ad36

**Comment by etiennebacher** [comment]
Likely related to https://github.com/pola-rs/polars/issues/19485

**Comment by eitsupi** [comment]
Interesting. As far as I can see from the lock file, pyo3 has not been incorporated into the dependencies.

**Comment by etiennebacher** [comment]
I had this issue when pulling this polars update in #19, it might be triggered by some of the features added in Cargo.toml there (I have reverted this polars update in the PR so I can still work on it without this error)

**Comment by eitsupi** [comment]
I see, that should the `dynamic_group_by` feature.
https://github.com/pola-rs/polars/blob/ec37a269393d5cebed53d8d1a461f5e8daf6f55e/crates/polars-lazy/Cargo.toml#L200-L207

**Comment by eitsupi** [comment]
I will bump polars to https://github.com/pola-rs/polars/tree/1c1574add6a0077aad69064e79c00414114fc28e in the main branch.

**Comment by eitsupi** [comment]
@etiennebacher Could you try merging?

**Comment by etiennebacher** [comment]
This works now, thanks for following up on that
