### ISSUE TITLE
Conversion of `NumericSexp` to `i64` doesn't fail with `NaN` while it should

### ISSUE THREAD

**Issue by etiennebacher** [eitsupi/neo-r-polars#29]
Currently, passing a `NaN` to `impl TryFrom<NumericSexp> for Wrap<Vec<i64>>` returns `[-2147483648]`. This means that `$reshape(NaN)` doesn't fail while it should.

@eitsupi There's already a `// TODO: update to support more bigger numeric`, do you want to fix this in `main`?

**Comment by yutannihilation** [comment]
Curious. `NumericSexp` itself should reject NaN.

https://github.com/yutannihilation/savvy/blob/a9ce0c6bf58ac8fb95d1dba427de991ca19b52e0/src/sexp/numeric.rs#L24

**Comment by yutannihilation** [comment]
Ah, no, sorry. It doesn't reject, but converts to NA, which is just i32::MIN to Rust.

**Comment by eitsupi** [comment]
Yeah, I think the conversion from an R vector (not a scalar) to a Rust vector would require rejecting NA (and NaN) on the R side.

**Comment by eitsupi** [comment]
Fixed by 942adee360be3701efa61c1b3ca1679aac23bbff
I know this is not efficient as it investigates a vector multiple times, but I think it works for now.
