### ISSUE TITLE
Plan for next weeks?

### ISSUE THREAD

**Issue by etiennebacher** [eitsupi/neo-r-polars#6]
A lot of issues in the main `polars` are linked to the rewrite and I have more time to contribute here. I see that some subnamespaces (e.g. datetime) are created but left to be filled but I don't want to start something if it turns out you're working on the same, so let me know where I should contribute.

**Comment by eitsupi** [comment]
Thank you!
I'll be busy with other things next week and won't have time to work here, so I'm sure you'll feel free to implement new methods and add documentation (although I haven't found the best pattern for testing expr methods yet).

Even if I were to work on it, I think it would be a function like `pl__concat` rather than an methods.

**Comment by etiennebacher** [comment]
Regarding tests, we could also write them only for DataFrame and then automatically modify for LazyFrame, as I do in `tidypolars`:

https://github.com/etiennebacher/tidypolars/blob/2236e6faaecf97c42bd0358150d5dd50c9f9b335/tests/testthat/helper.R#L39
https://github.com/etiennebacher/tidypolars/blob/main/tests/testthat/setup.R

**Comment by eitsupi** [comment]
For queries, there are helpers in this file to test against LazyFrame and DataFrame simultaneously.

https://github.com/eitsupi/neo-r-polars/blob/2672fce59b94c67655ac0ab7a13a1995db4da437/tests/testthat/helper-expections.R#L16-L25

But as for the expr method, I think it is usually overkill to use this.
I think for now we can just use nomal `expect_equal()` with DataFrame as like below, but I was just wondering if we could simplify it a bit more for expr tests.

```r
expect_equal(data$select(<something>), pl$select(<otherthing>))
```

**Comment by eitsupi** [comment]
Closing due to out of date.
